image: node:18-alpine

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

cache:
  paths:
    - node_modules/

# Test stage
test:
  stage: test
  script:
    - npm install
    - npm test
  only:
    - gitlab-ci
    - main

# Build stage
build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  only:
    - gitlab-ci
    - main

# Deploy to Vercel stage
deploy_vercel:
  stage: deploy
  image: node:18-alpine
  script:
    - npm install -g vercel
    - vercel --token $VERCEL_TOKEN --prod
  environment:
    name: production
    url: https://weather-app-pi-lyart-53.vercel.app
  only:
    - gitlab-ci
    - main

# Deploy to Docker Hub stage
deploy_docker:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
    DOCKER_TAG: $CI_COMMIT_REF_SLUG
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG
  only:
    - gitlab-ci
    - main 